#!/usr/bin/env python3
"""
sync_retail_skus.py — Weekly retail SKU sync

Reads the Glamnetic retail orders Google Sheet (1UG_DeOhihwesv4vQ6cKo0tjJ94jKz1pAHxmtpy1GVwQ),
extracts the freshest CUST SKU (retailer item number) per Glamnetic SKU per retailer,
then patches columns Q–U in the SKU Master sheet with any new or changed values.

The JSON (~/clicky-plus/data/sku-master.json) is regenerated by build_sku_master.py
which already reads Q–U; run this script BEFORE build_sku_master.py in the weekly routine.

Retailer groups (matched via COMPANY column on year tabs, tab name on walmart tab):
  Q = Ulta      — COMPANY containing ULTA or ULTA-DIGI
  R = Target    — COMPANY containing TARG
  S = Sephora   — COMPANY containing SEPH
  T = Dillard's — COMPANY containing DILL
  U = Walmart   — walmart tab (all rows); year tabs with COMPANY ~= WAL-MART / WALMART

Match strategy:
  Primary: SKU column exact match against SKU Master (col A)
  Fallback: UPC match (normalized to 12-digit)

Usage:
  python3 sync_retail_skus.py
"""

import json, re, os
from collections import defaultdict
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

RETAIL_SHEET_ID  = "1UG_DeOhihwesv4vQ6cKo0tjJ94jKz1pAHxmtpy1GVwQ"
CURATED_ID       = "1KtJ69B7dsvU0I5SnNMMxgf52iq7H_9-X6-ZKmC34Dzk"
TOKEN_PATH       = os.path.expanduser("~/.config/sheets-mcp/token.json")

RETAILER_COLS = {
    "ulta":     16,   # Q (0-based)
    "target":   17,   # R
    "sephora":  18,   # S
    "dillards": 19,   # T
    "walmart":  20,   # U (US + Canada combined)
}

RETAILER_PATTERNS = {
    "ulta":     re.compile(r"ulta", re.I),
    "target":   re.compile(r"\btarg", re.I),
    "sephora":  re.compile(r"seph", re.I),
    "dillards": re.compile(r"dill", re.I),
    "walmart":  re.compile(r"wal.?mart", re.I),
}

OVERRIDES = {
    # SKUs in the retail sheet that map to a different master SKU
    "TOOLS1005-IPSY": "TOOLS1005",
    "TOOLU1001":      "TOOLS1005",
    # Known non-master retail entries to skip
    "ANCHU1002": None, "24PCSANCH": None, "GLU1-HCD": None,
    "LASHU1001": None, "LASHU1002": None, "LASHU1005": None,
    "LASHA1009": None, "LASHL1007": None, "LASHV1015": None, "LASHP1010": None,
    "NAILS1602-B": None, "NAILS1604-B": None, "NAILS1606-B": None,
}

def upcnorm(u):
    d = re.sub(r"\D", "", u or "")
    return d.zfill(12) if 0 < len(d) <= 12 else d

def classify_retailer(company_value):
    """Return retailer key from COMPANY column value, or None."""
    for key, pat in RETAILER_PATTERNS.items():
        if pat.search(company_value or ""):
            return key
    return None

def is_year_tab(name):
    """True if tab name is a 4-digit year (2024, 2025, 2026, …)."""
    return bool(re.fullmatch(r"20\d{2}", name.strip()))

def read_retail_sheet(api):
    """
    Read retail orders sheet.

    Tab strategy:
      - Year tabs (2024, 2025, 2026, …): use COMPANY column to classify retailer.
        Read ALL year tabs so newest-wins logic spans all history.
      - 'walmart' tab: treat every row as retailer=walmart (COMPANY col may or
        may not be present; US + Canada rows both map to the same walmart column).
      - Any other tab (legacy name-based): classify by tab name pattern.

    Returns: { retailer_key: { glam_sku: cust_sku } }
    Newest order date wins when a SKU appears multiple times.
    """
    meta = api.get(spreadsheetId=RETAIL_SHEET_ID, fields="sheets.properties").execute()
    tab_names = [s["properties"]["title"] for s in meta["sheets"]]

    # maps: retailer -> { glam_sku -> (order_date_str, cust_sku) }
    best = defaultdict(dict)

    for tab in tab_names:
        # Decide how to classify rows in this tab
        if is_year_tab(tab):
            tab_retailer = None        # use COMPANY column per row
        elif re.search(r"\bwalmart\b", tab, re.I):
            tab_retailer = "walmart"   # all rows in this tab = walmart
        else:
            # Legacy tab named after retailer (ULTA, TARG, etc.)
            tab_retailer = classify_retailer(tab)

        try:
            result = api.values().get(
                spreadsheetId=RETAIL_SHEET_ID,
                range=f"'{tab}'!A1:Z1",
            ).execute()
            header = [str(c).strip().upper() for c in (result.get("values") or [[]])[0]]
        except Exception:
            continue

        def hcol(name):
            return header.index(name) if name in header else -1

        i_company  = hcol("COMPANY")
        i_sku      = hcol("SKU")
        i_cust_sku = hcol("CUST SKU")
        i_date     = hcol("ORDER DATE")

        if i_sku < 0 or i_cust_sku < 0:
            continue

        try:
            result = api.values().get(
                spreadsheetId=RETAIL_SHEET_ID,
                range=f"'{tab}'!A2:Z",
            ).execute()
            rows = result.get("values", [])
        except Exception:
            continue

        for row in rows:
            def g(i):
                return str(row[i]).strip() if i >= 0 and i < len(row) else ""

            raw_sku  = g(i_sku)
            cust_sku = g(i_cust_sku)
            order_dt = g(i_date)
            company  = g(i_company)

            if not raw_sku or not cust_sku:
                continue

            # Determine retailer
            if tab_retailer is not None:
                retailer = tab_retailer
            else:
                retailer = classify_retailer(company)
            if retailer is None:
                continue

            # Resolve master SKU
            if raw_sku in OVERRIDES:
                master_sku = OVERRIDES[raw_sku]
                if master_sku is None:
                    continue
            else:
                master_sku = raw_sku

            # Keep newest order date
            prev = best[retailer].get(master_sku)
            if prev is None or order_dt > prev[0]:
                best[retailer][master_sku] = (order_dt, cust_sku)

    # Flatten to { retailer: { sku: cust_sku } }
    return {
        retailer: {sku: v[1] for sku, v in skus.items()}
        for retailer, skus in best.items()
    }

def main():
    creds = Credentials.from_authorized_user_file(TOKEN_PATH)
    svc   = build("sheets", "v4", credentials=creds)
    sheets_api = svc.spreadsheets()

    print("Reading retail orders sheet…")
    retail_maps = read_retail_sheet(sheets_api)
    total_retail = sum(len(v) for v in retail_maps.values())
    print(f"  Found {total_retail} retail SKU mappings across {list(retail_maps.keys())}")

    # Read current SKU Master (A:A for SKU index, Q:T for existing retail values)
    print("Reading SKU Master…")
    result = sheets_api.values().get(
        spreadsheetId=CURATED_ID,
        range="'SKU Master'!A2:U",
    ).execute()
    sheet_rows = result.get("values", [])

    # Build index: sku -> row_index (0-based in sheet_rows)
    sku_to_idx = {}
    for i, row in enumerate(sheet_rows):
        sku = str(row[0]).strip() if row else ""
        if sku:
            sku_to_idx[sku] = i

    # Determine which cells need updating
    updates = []  # { range, values }
    changed = 0

    for retailer, sku_map in retail_maps.items():
        col_idx = RETAILER_COLS[retailer]
        col_letter = chr(ord("A") + col_idx)  # Q, R, S, or T

        for master_sku, cust_sku in sku_map.items():
            if master_sku not in sku_to_idx:
                continue
            row_idx = sku_to_idx[master_sku]
            row = sheet_rows[row_idx]
            current = str(row[col_idx]).strip() if col_idx < len(row) else ""

            if current == cust_sku:
                continue  # already current

            sheet_row_num = row_idx + 2  # +1 for header, +1 for 1-based
            updates.append({
                "range": f"'SKU Master'!{col_letter}{sheet_row_num}",
                "values": [[cust_sku]],
            })
            changed += 1

    if updates:
        sheets_api.values().batchUpdate(
            spreadsheetId=CURATED_ID,
            body={"valueInputOption": "RAW", "data": updates},
        ).execute()
        print(f"Updated {changed} retail SKU cells in the SKU Master sheet.")
    else:
        print("No retail SKU changes — sheet is already current.")

if __name__ == "__main__":
    main()
